server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  application:
    name: pr
  security:
    user:
      password: ${SECURITY_PASSWORD}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 1100
          max-idle: 300
          min-idle: 100
      timeout: 5000
jwt:
  access-expiration: 600000  # 10 min: 10min * 60 sec * 1000 millisecond
  refresh-expiration: 10800000  # 10800000 3 hours: 3hours * 60min * 60sec * 1000 millisecond
  private-key-file: ${PRIVATE_KEY_FILE}
  public-key-file: ${PUBLIC_KEY_FILE}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.orderhub.pr: DEBUG
